env:
  global:
    - MAKEFLAGS="-j $(nproc)"

language: perl
perl:
   - 5.30
   - 5.28

cache:
  directories:
  - ~/ghostscript-9.52
  - ~/perl_modules

before_install:
  - cpanm --quiet --notest local::lib
  - eval "$(perl -Mlocal::lib=~/perl_modules)"

install:
  - |
    # Installing ghostscript
    set -e
    pushd ~/
    if [ ! -d "ghostscript-9.52/lib" ]; then
        wget https://github.com/ArtifexSoftware/ghostpdl-downloads/releases/download/gs952/ghostscript-9.52.tar.gz
        tar -xf ghostscript-9.52.tar.gz
        pushd ghostscript-9.52 && ./configure --prefix=/usr && make && sudo make install && popd
    else
        echo "Using cached directory."
        pushd ghostscript-9.52 && sudo make install && popd
    fi
    popd
  - cpanm --quiet --installdeps --notest .
  - make PREFIX=/usr
  # Use perlbrew Perl instead of system one.
  - sed -i "s|^#!/usr/bin/perl$|#!/usr/bin/env perl|" ./ps2mail

jobs:
  include:
    - stage: test
      env: TEST_SUITE=tidy
      perl: 5.30

      install: |
        # Installing CPAN dependencies
        cpanm --quiet --notest \
        Code::TidyAll \
        Code::TidyAll::Plugin::Test::Vars \
        Perl::Critic \
        Perl::Tidy \
        Pod::Tidy

      script: tidyall -a --check-only || ( tidyall -a && git diff && false )
