version: 2
jobs:
  test:
    docker:
      - image: buildpack-deps:sid
    steps:
      - run:
          name: Exporting env vars
          command: |
            cat >> $BASH_ENV <<EOF
            export PATH=$PATH:$HOME/perl5/bin
            export PERL_CPANM_OPT=--local-lib=$HOME/perl5
            export PERL5LIB=$HOME/perl5/lib/perl5:$PERL5LIB
            EOF
      - checkout
      - run:
          name: Installing gettext
          command: apt-get -qq update; apt-get -qq install gettext

      - restore_cache:
          key: v9-ghostscript
      - run:
          name: Installing ghostscript
          command: |
            set -e
            pushd ~/
            if [ ! -d "ghostscript-9.50/lib" ]; then
                wget https://github.com/ArtifexSoftware/ghostpdl-downloads/releases/download/gs950/ghostscript-9.50.tar.gz
                tar -xf ghostscript-9.50.tar.gz
                pushd ghostscript-9.50 && ./configure --prefix=/usr && make && make install && popd
            else
                echo "Using cached directory."
                pushd ghostscript-9.50 && make install && popd
            fi
            popd
      - save_cache:
          key: v9-ghostscript
          paths:
            - ~/ghostscript-9.50

      - restore_cache:
          key: v4-perl_modules-{{ checksum "cpanfile" }}
      - run:
          name: Installing cpanm
          command: 'curl -L https://cpanmin.us | perl - App::cpanminus'
      - run:
          name: Installing CPAN dependencies
          command: cpanm --quiet --installdeps --notest .
      - save_cache:
          key: v4-perl_modules-{{ checksum "cpanfile" }}
          paths:
            - ~/perl5

      - run: make PREFIX=/usr
      - run: make test

  tidy:
    docker:
      - image: buildpack-deps:sid
    steps:
      - run:
          name: Exporting env vars
          command: |
            cat >> $BASH_ENV <<EOF
            export PATH=$PATH:$HOME/perl5/bin
            export PERL_CPANM_OPT=--local-lib=$HOME/perl5
            export PERL5LIB=$HOME/perl5/lib/perl5:$PERL5LIB
            EOF
      - checkout

      - restore_cache:
          key: v7-tidyall_dependencies
      - run:
          name: Installing cpanm
          command: 'curl -L https://cpanmin.us | perl - App::cpanminus'
      - run:
          name: Installing CPAN dependencies
          command: |
            cpanm --quiet --notest \
              Code::TidyAll \
              Code::TidyAll::Plugin::Test::Vars \
              Perl::Critic \
              Perl::Tidy \
              Pod::Tidy
      - save_cache:
          key: v7-tidyall_dependencies
          paths:
            - ~/perl5

      - run:
          name: Running tidyall
          command: |
            set -e
            tidyall --version
            perltidy --version | head -1
            perlcritic --version
            tidyall -a --check-only

workflows:
  version: 2
  test_and_tidy:
    jobs:
      - test
      - tidy
